language: python
python:
  - "3.9"

# Install dependencies.
install:
  - pip install -r requirements.txt

# Run linting and tests.
script:
  - pylint 

# Turn email notifications off.
notifications:
  email: false
