name: venv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn 
  - biopython
  - bcbio-gff
  - dna_features_viewer
  - seaborn
  - imbalanced-learn
  - category_encoders
  - hyperopt
  - chembl_webresource_client
  - rdkit
  - skrebate
  - pip
  - pip:
    - scprep
    - phate
    - gseapy

