name: venv
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn 
  - scipy
  - biopython
  - seaborn
  - xgboost
  - lightgbm
  - catboost
  - imbalanced-learn
  - category_encoders
  - hyperopt
  - os
  - scprep
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
